config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users, only: %i[index show edit update] do
    member do
      get 'profile'
    end
  end
  resources :petsitters, only: %i[index show new create edit update] do
    resources :bookings, only: %i[show new create edit update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :petsitter
end

app/models/petsitter.rb
class Petsitter < ApplicationRecord
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :petsitters, through: :bookings
  has_one_attached :profile_picture
  has_one_attached :pet_picture
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
  end

  def new
    @petsitter = Petsitter.find(params[:petsitter_id])
    @booking = Booking.new
  end

  def create
    @petsitter = Petsitter.find(params[:petsitter_id])
    @booking = Booking.new(booking_params)
    @booking.petsitter = @petsitter
    if @booking.save
      redirect_to user_path(current_user), notice: 'Booking was created successfully!'
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:date_from, :date_to, :comment, :status, :user_id, :petsitter_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # select 3 random petsitters
    @petsitters = Petsitter.all.sample(4)
  end

  def show
  end
end

app/controllers/petsitters_controller.rb
class PetsittersController < ApplicationController
  def index
    @petsitters = Petsitter.all

    if params[:location].present?
      @petsitters = find_petsitters_near(params[:location])
    end

    if params[:cat].present?
      @petsitters = @petsitters.merge(find_petsitters_by_description("%cats%"))
    end

    if params[:dog].present?
      @petsitters = @petsitters.merge(find_petsitters_by_description("%dogs%"))
    end

    showmap(@petsitters, params[:location])
  end

  def show
    @petsitter = Petsitter.find(params[:id])
  end

  private

  def find_petsitters_near(location)
    petsitters = Petsitter.near(location, 1)
    if petsitters.empty?
      flash.now[:alert] = "No petsitters found in this area"
      Petsitter.all
    else
      petsitters
    end
  end

  def showmap(petsitters, _location)
    @markers = petsitters.geocoded.map do |petsitter|
      {
        lat: petsitter.latitude,
        lng: petsitter.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { petsitter: petsitter }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def find_petsitters_by_description(description)
    Petsitter.where("description LIKE ?", description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find(params[:id])
    @bookings = @user.bookings
  end

  def show
    @user = User.find(params[:id])
    @bookings = @user.bookings
  end

  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container-bk">

<div>


  <div class="row justify-content-center">

    <div class="col-sm-6 booking-form">
    <h1 class="text-center mt-4">Secure Your Pet's Perfect Match!</h1>
      <%= simple_form_for [@petsitter, @booking] do |f| %>

      <div class="mb-3">
        <%= f.input :date_from, label: "From:", input_html: { class: 'form-control datepicker' } %>
      </div>

      <div class="mb-3">
        <%= f.input :date_to, label: "To:", input_html: { class: 'form-control datepicker' } %>
      </div>


      <div class="mb-3">
        <%= f.input :comment, label: "Leave a message!", input_html: { class: 'form-control' } %>
      </div>

        <%= f.hidden_field :user_id, value: current_user.id %>

        <div class="btn-light">
        <%= f.submit 'Create Booking', class: "btn btn-success" %>
        </div>


      <% end %>
    </div>
  </div>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetPal</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cabin&family=Sniglet&display=swap" rel="stylesheet">
  </head>

  <body>
    <!-- Start of Navbar -->
  <div class = "page-container">
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "favicon.ico" %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <%= image_tag "https://images.unsplash.com/photo-1632498301446-5f78baad40d0?q=80&w=500&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9nJTIwb3duZXJ8ZW58MHx8MHx8fDA%3D", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
                </div>
              </li>
            <% else %>
              <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <!-- End of NavbaR -->

  <!-- Start of Main Content -->
  <div class="main-content">
  <% if notice || alert %>
    <p class="notice  alert-light" role="alert"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  <!-- End of Main Content -->

    <!-- Start of Footer -->
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
        <a href="#"><i class="fab fa-youtube"></i></a>
      </div>
      <div class="footer-copyright">
        Copyright © 2024 PetPal, Inc.
      </div>
    </div>
  </div>
  </body>

</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Your Pet's Home Away from Home</h1>
    <p>Trustworthy Pet Sitting Services Tailored Just for You</p>
    <%= link_to "Book now", petsitters_path, class: "btn btn-primary large-button" %>
  </div>
</div>

<div class="yellow-banner card-heading-hp">

  <h2 style="font-weight:bold;">Meet some of our recent sitters</h2>

</div>

<div class="flex-box box-hm-pg">
  <% @petsitters.each do |petsitter| %>
    <div class="card home-pg" style="width: 18rem;">
      <%= image_tag petsitter.photo, class: "profile-img-hp" %>
      <div class="card-body">
        <h4 class="card-title"><%= petsitter.first_name %> <%= petsitter.last_name %></h4>
          <p class="card-text"><%= petsitter.short_description %></p>
          </div>
        <div class="bnow-btn">

          <%= link_to 'More info', petsitter_path(petsitter.id), class: "btn btn-success" %>

        </div>

    </div>
  <% end %>
</div>

<div class="yellow-banner card-heading-hp">

<h2 style="font-weight: bold">See what PetPal offers</h2>

</div>

<div class="card-group service-hp">
  <div class="card">

    <%= image_tag "s1.png", width: 200, class:"card-img-top" %>

    <div class="card-body">
      <h5 class="card-title">Explore the PetPal Experience</h5>
      <p class="card-text">Embark on a journey to discover the unparalleled care and companionship offered by PetPal.</p>
    </div>
  </div>
  <div class="card">
    <%= image_tag "s4.png", width: 200, class:"card-img-top" %>
    <div class="card-body">
      <h5 class="card-title">Unveil the PetPal Magic</h5>
      <p class="card-text">Peek behind the curtain and witness the magic that happens when passion meets pet care at PetPal.</p>
    </div>
  </div>
  <div class="card">
    <%= image_tag "s2.png", width: 200, class:"card-img-top" %>
    <div class="card-body">
      <h5 class="card-title">PetPal: Where Every Pawprint Matters</h5>
      <p class="card-text">See what PetPal has to offer, where every interaction, every service, is crafted to make a difference in your pets' lives.</p>
    </div>
  </div>
</div>

<div class="yellow-banner card-heading-hp">
  <h2 style="font-weight: bold">Hear it from PetPal users</h2>
</div>

<div class="card-group review-petpal">
  <div class="card review-homepage">
    <div class="card-body">
      <h6 class="card-title">Rating: ⭐⭐⭐⭐⭐</h6>
      <h5 class="card-title">PetPal exceeded my expectations! </h5>
      <p class="card-text">The attention to detail, from the initial meet-and-greet to the daily care routines, was impeccable. It's clear they genuinely care about pets. My dog, Max, is always thrilled to see his PetPal caretaker. Thank you for the excellent service!</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Billie E., 1 day ago</small>
    </div>
  </div>
  <div class="card review-homepage">
    <div class="card-body">
      <h6 class="card-title">Rating: ⭐⭐⭐⭐⭐</h6>
      <h5 class="card-title">PetPal's team of caretakers is fantastic</h5>
      <p class="card-text">They don't just feed and walk the pets; they truly connect with them. My two dogs, Bella and Rocky, were so well taken care of that I think they were a bit disappointed when I returned! I'm extremely grateful for the excellent service.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">lil W., 3 days ago</small>
    </div>
  </div>
  <div class="card review-homepage">
    <div class="card-body">
      <h6 class="card-title">Rating: ⭐⭐⭐⭐⭐</h6>
      <h5 class="card-title">PetPal is a lifesaver!</h5>
      <p class="card-text">I had to go on an unexpected business trip, and they took care of my fur babies with so much love and attention. The daily photo updates were a nice touch, and I returned to happy, healthy pets. Highly recommend!</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Jason B., 5 days ago</small>
    </div>
  </div>
</div>

app/views/petsitters/_info_window.html.erb
<div class="pop-up-window">
  <div class ="main-info">
    <%= image_tag petsitter.photo, size: "50x50", alt: "Petsitter Photo" %>
    <h3><%= "#{petsitter.first_name} #{petsitter.last_name}" %></h3>
  </div>
  <p><%= petsitter.address %></p>
  <%= link_to "Go to profile", petsitter_path(petsitter), class: "btn btn-primary", id: "window-btn"%>
</div>

app/views/petsitters/_marker.html.erb
<%= image_tag "favicon.ico", class: "rounded-image", alt: "Logo" %>

app/views/petsitters/index.html.erb
<div class = "results-container">
  <h1>Find your perfect Petsitter</h1>

  <%= form_tag(petsitters_path, :method => "get", remote: true, class: "form-inline") do %>
    <div class="input-group">
      <%= search_field_tag :location, params[:location], placeholder: "Enter the location", class: "form-control" %>
      <div class="checkbox">
        <div class="form-check form-check-inline">
          <div class="form-check form-check-inline">
            <%= check_box_tag :cat, params[:cat], class: "form-check-input"%>
            <label class="form-check-label">
              <i class="fa-solid fa-cat fa-2xl" style="color: #0a9e8f;"></i>
            </label>
          </div>
        </div>
        <div class="form-check form-check-inline">
          <%= check_box_tag :dog, params[:dog], class: "form-check-input" %>
          <label class="form-check-label">
              <i class="fa-solid fa-dog fa-2xl" style="color: #0a9e8f;"></i>
            </label>
        </div>
      </div>
        <%= button_tag "Search for petsitter", id: "search-btn", class: "btn-primary"%>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-warning">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class = "results">
<!-- Petsitter results -->
    <div class="result-cards">
      <% @petsitters.each do |petsitter| %>
        <%= link_to petsitter_path(petsitter), id: "link" do %>
          <div class="result-card">
            <%= image_tag(petsitter.photo, size: "120x120", alt: "Petsitter Photo") %>
            <div class="result-card-infos">
              <h3><%= petsitter.first_name %> <%= petsitter.last_name %></h3>
              <p id="mini-description"><%=petsitter.description%></p>
              <p>From <em id="rate"><%= rand(10..30)%>$</em> per hour</p>
            </div>
          </div>
        <% end%>
      <% end%>
    </div>
<!-- End of Petsitter Results -->
<!-- Map -->
    <div class = "map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>
</div>
<!-- End of Map -->

app/views/petsitters/show.html.erb
  <div class="d-flex profile">
    <div class="card mb-3 full-card" style="width: 70vw;">
      <div class="row g-0 pic-bio">
        <div class="col-md-4 set-pic">
          <%= image_tag @petsitter.photo, class: "img-fluid rounded-start image" %>
        </div>
        <div class="col-md-8">
          <div class="card-body card-bio">
            <h3 class="card-title" style="font-weight:bold"><%= @petsitter.first_name %> <%= @petsitter.last_name %></h3>
            <p class="card-text"><%= @petsitter.description %></p>
            <p class="card-text">
            <div class="bnow-btn">

            </div>
              <small class="text-muted bnow-btn">
                <%= link_to 'Book Now', new_petsitter_booking_path(petsitter_id: @petsitter.id), class: "btn btn-success" %>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>




<div class="d-flex justify-content-center review">
<h3>Reviews</h3>
</div>

<div class="card-group review-scn">

  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @petsitter.rt %></h5>
      <p class="card-text"><%= @petsitter.review %></p>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @petsitter.rt %></h5>
      <p class="card-text"><%= @petsitter.review1 %></p>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @petsitter.rt %></h5>
      <p class="card-text"><%= @petsitter.review2 %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-6 mb-4">
      <!-- Account Info Card -->
      <div class="card-container">
        <div class="card-user">
          <img src="https://images.unsplash.com/photo-1632498301446-5f78baad40d0?q=80&w=500&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZG9nJTIwb3duZXJ8ZW58MHx8MHx8fDA%3D" class="profile-pic" />
          <% if @user %>
            <div class="card-user-infos mt-3">
              <p class="user-name text-center"><strong>Emily</strong></p>
              <p class="text-center location"><strong>London</strong> <span class="location-pin">📍</span></p>
              <p>Hello pet-loving community! I'm Emily, and my beloved four-legged companion is Gina, the ultimate jetsetter pup. As we embark on our next adventure, I'm on the lookout for the perfect pet-sitter to provide a warm and loving home for Gina while I'm away. If you're someone who understands the importance of cuddles, playtime, and a little wanderlust, join us in making sure Gina has the best staycation ever! Your home could be the perfect pitstop for Gina's vacation. Let's chat and ensure a tail-wagging experience</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-4">
      <!-- My Bookings Card -->
      <div class="card-container">
        <h2>My Bookings:</h2>
        <% @bookings.each do |booking| %>
          <div class="card-booking">
            <div class="booking-header">
              <!-- Petsitter Avatar -->
              <%= image_tag booking.petsitter.photo, class: " avatar img-fluid" %>
              <!-- Booking Details -->
              <div class="booking-details">
                <p>
                  <h3><%= booking.petsitter.first_name %> <button class="btn btn-warning">Pending</button></h3>
                </p>
                <p><strong>From:</strong> <%= booking.date_from %> <strong>to:</strong> <%= booking.date_to %></p>
                <p>Message sent to <%= booking.petsitter.first_name %>: <%= booking.comment %></p>
              </div>
            </div>
          </div>
        <% end %>
      <%= link_to "Make another booking", petsitters_path, class: "btn btn-primary"%>
      </div>
    </div>
  </div>
</div>